version: "3.8"
services:
  app:
    build: .
    container_name: backend-assignment
    ports:
      - "3000:3000"
    env_file: .env
    volumes:
      - ./uploads:/app/uploads
    restart: unless-stopped
